MovieManage/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('',include('movies.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls'))
]

accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"
urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('', views.index, name="index"),
    path('<int:id>/', views.detail, name="detail"),
    path('<int:id>/follow/', views.follow, name="follow"),
]

movies/urls.py
from django.urls import path
from . import views

app_name="movies"

urlpatterns = [
    path('',views.index, name="index"),
    path('<int:id>/',views.detail, name="detail"),
    path('<int:id>/reviews/new/', views.create_review, name="create_review"),
    path('<int:movie_id>/reviews/<int:review_id>/delete/', views.delete_review, name="delete_review"),
    path('<int:id>/like/', views.movie_like, name="movie_like"),
    
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
# Create your models here.

class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followings")

movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=20)

class Movie(models.Model):
    title = models.CharField(max_length=30)
    audience = models.IntegerField()
    poster_url = models.CharField(max_length=140)
    description = models.TextField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_movies")

class Review(models.Model):
    content = models.CharField(max_length=140)
    score = models.IntegerField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm

class UserCustomCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'first_name', 'last_name',)

movies/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('content', 'score', )

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from .forms import UserCustomCreationForm
from .models import User

# Create your views here.

def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:index')

    if request.method == "POST":
        form = UserCustomCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = UserCustomCreationForm()
    context={
        'form':form
    }
    return render(request,'accounts/forms.html',context)

def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')

    if request.method == "POST":
        form = AuthenticationForm(request,request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('movies:index')
    else:
        form = AuthenticationForm()
    context={
        'form':form
    }
    return render(request,'accounts/forms.html',context)

def logout(request):
    auth_logout(request)
    return redirect('movies:index')

def index(request):
    user_model = get_user_model()
    user_list = user_model.objects.all()
    context = {
        'user_list':user_list
    }
    return render(request, 'accounts/index.html', context)
def detail(request, id):
    user_model = get_user_model()
    user_info = get_object_or_404(user_model, id=id)

    context= {
        'user_info':user_info
    }
    return render(request,'accounts/detail.html', context)

def follow(request, id):
    you = get_object_or_404(User, id=id)
    me = request.user
    if not you==me:
        if me in you.followers.all():
            you.followers.remove(me)
        else:
            you.followers.add(me)
            # me.followings.add(you)

    return redirect('accounts:detail', id)

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie, Review
from .forms import ReviewForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies
    }
    return render(request, 'movies/index.html', context)

def detail(request, id):
    movie = get_object_or_404(Movie, id=id)
    form = ReviewForm()
    context = {
        'movie': movie,
        'form': form,
    }
    return render(request, 'movies/detail.html', context)

@login_required    
def create_review(request, id):
    movie = get_object_or_404(Movie, id=id)
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.movie = movie
            review.save()
            return redirect('movies:detail', id)
        return redirect('movies:index')

@login_required
def delete_review(request,movie_id,review_id):
    if request.method == "POST":
        review = get_object_or_404(Review, id=review_id)
        if request.user == review.user:
            review.delete()
    return redirect('movies:detail', movie_id)

@login_required
def movie_like(request, id):
    if request.method == "POST":
        movie = get_object_or_404(Movie, id=id)
        user = request.user
        if user in movie.like_users.all():
            movie.like_users.remove(user)
        else:
            movie.like_users.add(user)
        
        return redirect('movies:detail', id)
    

MovieManage/templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  {% bootstrap_css %}
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'movies:index' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNavAltMarkup">
      <div class="navbar-nav ">
          <a class="nav-item nav-link" href="{% url 'accounts:index' %}">유저 정보보기</a>
        {% if user.is_authenticated %}
          <p class="nav-item nav-link">{{user}}</p>
          <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
        {% else %}
          <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
          <a class="nav-item nav-link" href="{% url 'accounts:login' %}">로그인</a>
        {% endif %}
      </div>
    </div>
  </nav>
  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
</body>
</html>

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% block body %}
<h2>아이디 : {{user_info.username}}</h2>
<h2>성 : {{user_info.first_name}}</h2>
<h2>이름 : {{user_info.last_name}}</h2>
<hr>
<h3>작성한 평점 정보</h3>
{% for review in user_info.review_set.all %}
  <h5>{{review.movie.title}}</h5>
  <h5>한줄평 : {{review.content}} 평점 : {{review.score}}</h5>
{% endfor %}
<hr>
<h5>팔로워: {{user_info.followers.all | length}}</h5>
<h5>팔로잉: {{user_info.followings.all | length}}</h5>
{% if user.is_authenticated and user != user_info %}
    <a href="{% url 'accounts:follow' user_info.id %}">팔로우</a>
{% endif %}

<hr>
<h3>좋아하는 영화</h3>
<div class="row">
{% for movie in user_info.like_movies.all %}
  <div class="card col-3 my-3 mx-1" style="width: 18rem;">
    <a href="{% url 'movies:detail' movie.id %}"><img src="{{movie.poster_url}}" class="card-img-top" alt="..."></a>
    <div class="card-body">
      <h5 class="card-title">{{movie.title}}</h5>
    </div>
  </div>
{% endfor %}
</div>
<hr>
{% endblock %}

accounts/templates/accounts/forms.html
{% extends 'base.html' %}
{% block body %}
<form action=""method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>
{% endblock %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% block body %}
<h2 class="my-2">사용자 목록</h2>
{% for user_info in user_list %}
  <a href="{% url 'accounts:detail' user_info.id %}"><h5>{{user_info.username}}</h5></a>
{% endfor %}
{% endblock %}

movies/templates/movies/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
  <div class="jumbotron">
    <div class="row">
      <div class="d-inline-flex align-items-start">  
        <div class="d-inline-flex mx-3">
          <img src="{{movie.poster_url}}" alt="" style="width: 26rem;">
        </div>
        <div class="mx-3">
          <h1 class="display-4">{{movie.title}}</h1>
          <span>누적 관객수 : {{movie.audience}}</span>
          <h3 class="my-3"> 줄거리 </h3>
          <p>{{movie.description}}</p>

          <form action="{% url 'movies:movie_like' movie.id %}" method="POST">
            {% csrf_token %}
            {% if user in movie.like_users.all %}
              <input type="submit" value="좋아요 취소" class="btn btn-primary">
            {% else %}
              <input type="submit" value="좋아요" class="btn btn-primary">
            {% endif %}
          </form>
          <p>{{movie.like_users.count}}</p>
        </div>
      </div>

    </div>
  </div>
    {% if user.is_authenticated %}
    <form action="{% url 'movies:create_review' movie.id %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" value="제출" class="btn btn-primary">
    </form>
    {% endif %}
  
  <hr>
  {% for review in movie.review_set.all %}
    <div class="alert alert-primary d-flex justify-content-between" role="alert">
      <p> 한줄평 : {{review.content}}</p>
      <p> 평점 :  {{review.score}}</p>
      
      {% if review.user == user %}
        <form action="{% url 'movies:delete_review' movie.id review.id %}" method="POST">
          {% csrf_token %}
          <input type="submit" class="btn btn-danger" value="삭제">
        </form>
      {% endif %}
    </div>
  {% endfor %}

  
{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}
{% block body %}
  <div class="row">
    {% for movie in movies %}
      <div class="card" style="width: 18rem;">
        <a href="{% url 'movies:detail' movie.id %}"><img src="{{movie.poster_url}}" class="card-img-top" alt="..."></a>
        <div class="card-body">
          <h5 class="card-title">{{movie.title}}</h5>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}